# ensure running in a container for fast boot, travis has these requirements:
sudo: false
dist: 'trusty'

# these are executed in order. each must pass for the next to be run
stages:
  - precache # warm up cache for default Node.js version
  - lint-n-test # lint and run tests
  - name: deploy
    if: branch = master AND type = push

# defaults
language: node_js
node_js: '10.15' # equivalent to node 10.15.x

env: COVERALLS_PARALLEL=true COVERAGE=true

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: precache
      install:
        - travis_wait npm i
      script: true

    - stage: lint-n-test
      name: Lint contracts and frontend app, tests and coverage report
      install: pwd # override to avoid npm i again
      script:
        - npm run lint
        - travis_wait 60 npm run coverage
      after_success: npm run coveralls

    - stage: deploy
      before_install:
      - mkdir $HOME/.aragon
      - openssl aes-256-cbc -K $encrypted_547551ebf6e1_key -iv $encrypted_547551ebf6e1_iv
        -in shared/deployments/rinkeby_key.json.enc -out $HOME/.aragon/rinkeby_key.json -d
      - ls $HOME/.aragon
      install:
        - travis_wait npm i -g @aragon/cli@6.4.1
        - npm i
      script: npm run publish:cd

notifications:
  webhooks: https://coveralls.io/webhook
  email:
    recipients:
      - jobs@autark.xyz
    if: branch = master

  # Only build pushes to master. All pull requests still build
branches:
  only:
  - master
