# ensure running in a container for fast boot, travis has these requirements:
sudo: false
dist: 'trusty'

# these are executed in order. each must pass for the next to be run
stages:
  - precache # warm up cache for default Node.js version
  - lint # lint code and docs
  - test # all tests

# defaults
language: node_js
node_js: '11'
cache:
  directories:
    - $HOME/.npm
    - node_modules

jobs:
  include:
    - stage: precache
      script: true

    - stage: lint
      name: Lint contracts and frontend apps
      install: pwd # override to avoid npm i again
      script: npm run lint

    - stage: test
      script: travis_wait 60 npm run coverage
      name: Home app tests and coverage report
      after_success: npm run coveralls

notifications:
  email: false
